import type { IndicatorModuleConfig } from '../types/indicators';

export const INDICATOR_MODULES: IndicatorModuleConfig[] = [
  {
    id: 'uf',
    label: 'UF',
    unit: 'CLP',
    decimals: 2,
    chartPoints: 30,
    minAxisSpanPct: 2,
    freshness: { kind: 'sameDay' },
    sources: ['mindicador', 'findic'],
  },
  {
    id: 'dolar',
    label: 'Dólar observado',
    unit: 'CLP',
    decimals: 2,
    chartPoints: 30,
    minAxisSpanPct: 2,
    freshness: { kind: 'maxAgeDays', days: 4 },
    sources: ['mindicador', 'findic'],
  },
  {
    id: 'euro',
    label: 'Euro',
    unit: 'CLP',
    decimals: 2,
    chartPoints: 30,
    minAxisSpanPct: 2,
    freshness: { kind: 'maxAgeDays', days: 4 },
    sources: ['mindicador', 'findic'],
  },
  {
    id: 'utm',
    label: 'UTM',
    unit: 'CLP',
    decimals: 0,
    chartPoints: 12,
    minAxisSpanPct: 2,
    freshness: { kind: 'sameMonth' },
    sources: ['mindicador', 'findic'],
  },
  {
    id: 'libra_cobre',
    label: 'Cobre',
    unit: 'USD_PER_LB',
    decimals: 2,
    chartPoints: 30,
    minAxisSpanPct: 2,
    freshness: { kind: 'maxAgeDays', days: 4 },
    sources: ['mindicador', 'findic'],
  },
];
